/**
 * THIRD-PARTY-NOTICES 생성기.
 * 번들되는 npm 패키지의 라이선스 전문 + 벤더링/런타임 다운로드 항목을 합쳐
 * src/renderer/src/generated/third-party-notices.txt 로 출력한다 (앱 내 설정 화면에서 표시).
 * 실행: pnpm gen:notices  (의존성 추가/변경 시 재실행 후 커밋)
 */

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'fs'
import { dirname, join, resolve } from 'path'
import { fileURLToPath } from 'url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8'))

// dependencies 전부 + 번들되는 devDependencies (electron 본체 고지는 배포물의
// LICENSE.electron.txt / LICENSES.chromium.html 이 담당하지만 목록에는 포함한다)
const bundledPackages = [...Object.keys(pkg.dependencies ?? {}), 'react', 'react-dom', 'electron']

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type -- 타입 표기 불가한 .mjs
function readLicenseText(pkgDir) {
  let entries
  try {
    entries = readdirSync(pkgDir)
  } catch {
    return null
  }
  const name = entries.find((f) => /^(licen[cs]e|copying)(\.|$)/i.test(f))
  return name ? readFileSync(join(pkgDir, name), 'utf-8').trim() : null
}

const divider = '\n' + '='.repeat(72) + '\n'
const parts = []

parts.push(
  `Karaoke Player — Third-Party Notices\n` +
    `이 문서는 이 애플리케이션에 포함되거나 실행 시 사용되는 서드파티 소프트웨어의\n` +
    `저작권 및 라이선스 고지를 담는다. (generated by scripts/generate-notices.mjs)`
)

// ── 1. 번들되는 npm 패키지 ──
for (const name of bundledPackages.sort()) {
  const pkgDir = join(root, 'node_modules', name)
  let meta
  try {
    meta = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf-8'))
  } catch {
    console.error(`skip (not installed): ${name}`)
    continue
  }
  const license = typeof meta.license === 'string' ? meta.license : JSON.stringify(meta.license)
  const text = readLicenseText(pkgDir)
  parts.push(
    `${name} v${meta.version} — ${license}\n${meta.homepage ?? ''}\n\n` +
      (text ?? '(라이선스 전문은 패키지 배포본에 포함되어 있지 않음 — 위 라이선스 식별자를 따른다)')
  )
}

// ── 2. 벤더링된 코드 ──
const lgpl = readFileSync(join(root, 'scripts', 'licenses', 'LGPL-2.1.txt'), 'utf-8').trim()
parts.push(
  `SoundTouchJS v0.3.0 — LGPL-2.1 (벤더링)\n` +
    `https://github.com/cutterbl/SoundTouchJS\n\n` +
    `이 앱은 soundtouchjs v0.3.0을 src/renderer/public/worklets/soundtouch-worklet.js 에\n` +
    `벤더링해 AudioWorklet 피치 시프트에 사용한다. 원본 출처와 수정 사실은 해당 파일\n` +
    `헤더에 명시되어 있으며, 파일은 앱 코드와 분리된 독립 스크립트로 유지된다.\n\n` +
    lgpl
)

parts.push(
  `Material Design Icons — Apache-2.0\n` +
    `https://github.com/google/material-design-icons\n\n` +
    `react-icons 패키지를 통해 포함되는 Material Design 아이콘은 Apache License 2.0을 따른다.`
)

parts.push(
  `Electron / Chromium / Node.js\n\n` +
    `Electron 및 그에 포함된 Chromium·Node.js 구성요소의 상세 고지는 배포판 루트의\n` +
    `LICENSE.electron.txt 와 LICENSES.chromium.html 파일을 참조한다.`
)

// ── 3. 첫 실행 시 다운로드되는 Python 런타임 (재배포하지 않음) ──
parts.push(
  `Python 사이드카 런타임 (첫 실행 시 사용자의 머신에서 PyPI로부터 다운로드되며,\n` +
    `이 배포물에는 포함되지 않는다. 각 프로젝트의 라이선스를 따른다)\n\n` +
    [
      'demucs — MIT (https://github.com/adefossez/demucs)',
      'torch — BSD-3-Clause (https://pytorch.org)',
      'torchaudio — BSD-2-Clause (https://github.com/pytorch/audio)',
      'faster-whisper — MIT (https://github.com/SYSTRAN/faster-whisper)',
      'mutagen — GPL-2.0-or-later (https://github.com/quodlibet/mutagen)',
      'uroman — Apache-2.0 (https://github.com/isi-nlp/uroman)',
      'lemon-pyopenjtalk-prebuilt (pyopenjtalk) — MIT (https://github.com/r9y9/pyopenjtalk)',
      'soundfile — BSD-3-Clause (https://github.com/bastibe/python-soundfile)'
    ].join('\n')
)

// ── 4. zip 배포판 동봉 도구 (uv/deno는 MSIX에도 포함, yt-dlp는 zip 전용) ──
const licDir = join(root, 'scripts', 'licenses')
const uvMit = readFileSync(join(licDir, 'uv-LICENSE-MIT.txt'), 'utf-8').trim()
const uvApache = readFileSync(join(licDir, 'uv-LICENSE-APACHE.txt'), 'utf-8').trim()
const denoLicense = readFileSync(join(licDir, 'deno-LICENSE.md'), 'utf-8').trim()
const ytdlpLicense = readFileSync(join(licDir, 'yt-dlp-LICENSE.txt'), 'utf-8').trim()

parts.push(
  `uv v0.12.9 — MIT OR Apache-2.0\n` +
    `https://github.com/astral-sh/uv\n\n` +
    `zip·MSIX 배포판에 동봉되어 sidecar 부트스트랩(uv sync)에 사용된다. 듀얼 라이선스이므로\n` +
    `두 전문을 모두 싣는다.\n\n` +
    uvMit +
    '\n\n' +
    uvApache
)

parts.push(
  `deno v2.9.6 — MIT\n` +
    `https://github.com/denoland/deno\n\n` +
    `zip·MSIX 배포판에 동봉되어 yt-dlp의 JS 챌린지 런타임(--js-runtimes deno:<경로>)으로 사용된다.\n\n` +
    denoLicense
)

parts.push(
  `yt-dlp v2026.08.19 — Unlicense\n` +
    `https://github.com/yt-dlp/yt-dlp\n\n` +
    `zip 배포판에만 동봉된다. MSIX(Store)판에는 yt-dlp가 포함되지 않는다 — Microsoft Store\n` +
    `정책상 YouTube 다운로드 도구는 거부 사유이므로 배포 채널을 분리했다 (스펙 001 §4.2).\n\n` +
    ytdlpLicense
)

const outDir = join(root, 'src', 'renderer', 'src', 'generated')
mkdirSync(outDir, { recursive: true })
const outPath = join(outDir, 'third-party-notices.txt')
writeFileSync(outPath, parts.join(divider) + '\n', 'utf-8')
console.log(`written: ${outPath} (${parts.length} sections)`)
